export enum EventCategory {
  PROJECT = 'project',
  CONTRIBUTION = 'contribution',
  MILESTONE = 'milestone',
  GOVERNANCE = 'governance',
  TOKEN = 'token',
  POOL = 'pool',
  PRICE = 'price',
  MODULE = 'module',
  ADMIN = 'admin',
  REPUTATION = 'reputation',
  SYSTEM = 'system',
}

export enum CanonicalEventType {
  PROJECT_CREATED = 'project.created',
  PROJECT_VERIFIED = 'project.verified',
  PROJECT_REJECTED = 'project.rejected',
  PROJECT_CANCELED = 'project.canceled',
  PROJECT_EXPIRED = 'project.expired',
  PROJECT_PROPOSED = 'project.proposed',
  CONTRIBUTION_DEPOSITED = 'contribution.deposited',
  CONTRIBUTION_REFUNDED = 'contribution.refunded',
  CONTRIBUTION_PAID_OUT = 'contribution.paid_out',
  CONTRIBUTION_CLAWED_BACK = 'contribution.clawed_back',
  FEE_DEDUCTED = 'fee.deducted',
  MILESTONE_APPROVED = 'milestone.approved',
  MILESTONE_APPROVED_BY_VOTE = 'milestone.approved_by_vote',
  MILESTONE_DISPUTED = 'milestone.disputed',
  MILESTONE_DISPUTE_RESOLVED = 'milestone.dispute_resolved',
  MILESTONE_VOTE_STARTED = 'milestone.vote_started',
  MILESTONE_VOTE_CAST = 'milestone.vote_cast',
  GOVERNANCE_PROPOSAL_CREATED = 'governance.proposal_created',
  GOVERNANCE_PROPOSAL_EXECUTED = 'governance.proposal_executed',
  GOVERNANCE_PROPOSAL_CANCELLED = 'governance.proposal_cancelled',
  GOVERNANCE_PROPOSAL_EXPIRED = 'governance.proposal_expired',
  GOVERNANCE_SIGNATURE_COLLECTED = 'governance.signature_collected',
  GOVERNANCE_MULTISIG_CONFIGURED = 'governance.multisig_configured',
  TOKEN_BURNED = 'token.burned',
  TOKEN_VESTING_CREATED = 'token.vesting_created',
  TOKEN_CLAIMED = 'token.claimed',
  TOKEN_STREAM_CREATED = 'token.stream_created',
  TOKEN_DELEGATE_APPROVED = 'token.delegate_approved',
  TOKEN_DELEGATE_REVOKED = 'token.delegate_revoked',
  TOKEN_DELEGATED_CLAIM = 'token.delegated_claim',
  POOL_ROUND_CREATED = 'pool.round_created',
  POOL_FUNDED = 'pool.funded',
  POOL_PROJECT_APPROVED = 'pool.project_approved',
  POOL_PROJECT_REMOVED = 'pool.project_removed',
  POOL_CONTRIBUTION_RECORDED = 'pool.contribution_recorded',
  POOL_ROUND_FINALIZED = 'pool.round_finalized',
  POOL_MATCH_DISTRIBUTED = 'pool.match_distributed',
  POOL_ALL_MATCHES_DISTRIBUTED = 'pool.all_matches_distributed',
  PRICE_UPDATED = 'price.updated',
  PRICE_ORACLE_UPDATED = 'price.oracle_updated',
  MODULE_REGISTERED = 'module.registered',
  MODULE_UPDATED = 'module.updated',
  MODULE_DEACTIVATED = 'module.deactivated',
  MODULE_ACTIVATED = 'module.activated',
  ADMIN_UPGRADED = 'admin.upgraded',
  ADMIN_CHANGED = 'admin.changed',
  ADMIN_TRANSFERRED = 'admin.transferred',
  ADMIN_PAUSED = 'admin.paused',
  ADMIN_UNPAUSED = 'admin.unpaused',
  ADMIN_FEE_CONFIG_CHANGED = 'admin.fee_config_changed',
  ADMIN_STORAGE_MIGRATED = 'admin.storage_migrated',
  ADMIN_VERIFICATION_OVERRIDDEN = 'admin.verification_overridden',
  REPUTATION_UPDATED = 'reputation.updated',
  REPUTATION_BADGE_GRANTED = 'reputation.badge_granted',
  REPUTATION_BADGE_REVOKED = 'reputation.badge_revoked',
  REPUTATION_PENALTY_APPLIED = 'reputation.penalty_applied',
  SYSTEM_ANOMALY = 'system.anomaly',
  SYSTEM_SENTIMENT_SPIKE = 'system.sentiment_spike',
  SYSTEM_ALERT = 'system.alert',
}

const CATEGORY_MAP: Record<CanonicalEventType, EventCategory> = {
  [CanonicalEventType.PROJECT_CREATED]: EventCategory.PROJECT,
  [CanonicalEventType.PROJECT_VERIFIED]: EventCategory.PROJECT,
  [CanonicalEventType.PROJECT_REJECTED]: EventCategory.PROJECT,
  [CanonicalEventType.PROJECT_CANCELED]: EventCategory.PROJECT,
  [CanonicalEventType.PROJECT_EXPIRED]: EventCategory.PROJECT,
  [CanonicalEventType.PROJECT_PROPOSED]: EventCategory.PROJECT,
  [CanonicalEventType.CONTRIBUTION_DEPOSITED]: EventCategory.CONTRIBUTION,
  [CanonicalEventType.CONTRIBUTION_REFUNDED]: EventCategory.CONTRIBUTION,
  [CanonicalEventType.CONTRIBUTION_PAID_OUT]: EventCategory.CONTRIBUTION,
  [CanonicalEventType.CONTRIBUTION_CLAWED_BACK]: EventCategory.CONTRIBUTION,
  [CanonicalEventType.FEE_DEDUCTED]: EventCategory.CONTRIBUTION,
  [CanonicalEventType.MILESTONE_APPROVED]: EventCategory.MILESTONE,
  [CanonicalEventType.MILESTONE_APPROVED_BY_VOTE]: EventCategory.MILESTONE,
  [CanonicalEventType.MILESTONE_DISPUTED]: EventCategory.MILESTONE,
  [CanonicalEventType.MILESTONE_DISPUTE_RESOLVED]: EventCategory.MILESTONE,
  [CanonicalEventType.MILESTONE_VOTE_STARTED]: EventCategory.MILESTONE,
  [CanonicalEventType.MILESTONE_VOTE_CAST]: EventCategory.MILESTONE,
  [CanonicalEventType.GOVERNANCE_PROPOSAL_CREATED]: EventCategory.GOVERNANCE,
  [CanonicalEventType.GOVERNANCE_PROPOSAL_EXECUTED]: EventCategory.GOVERNANCE,
  [CanonicalEventType.GOVERNANCE_PROPOSAL_CANCELLED]: EventCategory.GOVERNANCE,
  [CanonicalEventType.GOVERNANCE_PROPOSAL_EXPIRED]: EventCategory.GOVERNANCE,
  [CanonicalEventType.GOVERNANCE_SIGNATURE_COLLECTED]: EventCategory.GOVERNANCE,
  [CanonicalEventType.GOVERNANCE_MULTISIG_CONFIGURED]: EventCategory.GOVERNANCE,
  [CanonicalEventType.TOKEN_BURNED]: EventCategory.TOKEN,
  [CanonicalEventType.TOKEN_VESTING_CREATED]: EventCategory.TOKEN,
  [CanonicalEventType.TOKEN_CLAIMED]: EventCategory.TOKEN,
  [CanonicalEventType.TOKEN_STREAM_CREATED]: EventCategory.TOKEN,
  [CanonicalEventType.TOKEN_DELEGATE_APPROVED]: EventCategory.TOKEN,
  [CanonicalEventType.TOKEN_DELEGATE_REVOKED]: EventCategory.TOKEN,
  [CanonicalEventType.TOKEN_DELEGATED_CLAIM]: EventCategory.TOKEN,
  [CanonicalEventType.POOL_ROUND_CREATED]: EventCategory.POOL,
  [CanonicalEventType.POOL_FUNDED]: EventCategory.POOL,
  [CanonicalEventType.POOL_PROJECT_APPROVED]: EventCategory.POOL,
  [CanonicalEventType.POOL_PROJECT_REMOVED]: EventCategory.POOL,
  [CanonicalEventType.POOL_CONTRIBUTION_RECORDED]: EventCategory.POOL,
  [CanonicalEventType.POOL_ROUND_FINALIZED]: EventCategory.POOL,
  [CanonicalEventType.POOL_MATCH_DISTRIBUTED]: EventCategory.POOL,
  [CanonicalEventType.POOL_ALL_MATCHES_DISTRIBUTED]: EventCategory.POOL,
  [CanonicalEventType.PRICE_UPDATED]: EventCategory.PRICE,
  [CanonicalEventType.PRICE_ORACLE_UPDATED]: EventCategory.PRICE,
  [CanonicalEventType.MODULE_REGISTERED]: EventCategory.MODULE,
  [CanonicalEventType.MODULE_UPDATED]: EventCategory.MODULE,
  [CanonicalEventType.MODULE_DEACTIVATED]: EventCategory.MODULE,
  [CanonicalEventType.MODULE_ACTIVATED]: EventCategory.MODULE,
  [CanonicalEventType.ADMIN_UPGRADED]: EventCategory.ADMIN,
  [CanonicalEventType.ADMIN_CHANGED]: EventCategory.ADMIN,
  [CanonicalEventType.ADMIN_TRANSFERRED]: EventCategory.ADMIN,
  [CanonicalEventType.ADMIN_PAUSED]: EventCategory.ADMIN,
  [CanonicalEventType.ADMIN_UNPAUSED]: EventCategory.ADMIN,
  [CanonicalEventType.ADMIN_FEE_CONFIG_CHANGED]: EventCategory.ADMIN,
  [CanonicalEventType.ADMIN_STORAGE_MIGRATED]: EventCategory.ADMIN,
  [CanonicalEventType.ADMIN_VERIFICATION_OVERRIDDEN]: EventCategory.ADMIN,
  [CanonicalEventType.REPUTATION_UPDATED]: EventCategory.REPUTATION,
  [CanonicalEventType.REPUTATION_BADGE_GRANTED]: EventCategory.REPUTATION,
  [CanonicalEventType.REPUTATION_BADGE_REVOKED]: EventCategory.REPUTATION,
  [CanonicalEventType.REPUTATION_PENALTY_APPLIED]: EventCategory.REPUTATION,
  [CanonicalEventType.SYSTEM_ANOMALY]: EventCategory.SYSTEM,
  [CanonicalEventType.SYSTEM_SENTIMENT_SPIKE]: EventCategory.SYSTEM,
  [CanonicalEventType.SYSTEM_ALERT]: EventCategory.SYSTEM,
};

export function getCategory(eventType: CanonicalEventType): EventCategory {
  return CATEGORY_MAP[eventType];
}
